"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

import sys
sys.setrecursionlimit(2000)

from setuptools import setup

APP = ['main.py']

'''
DATA_FILES = ['./myenv/lib/python3.11/site-packages/whisper/assets/mel_filters.npz', 
'myenv/lib/python3.11/site-packages/whisper/assets', 
'myenv/lib/python3.11/site-packages/whisper/assets', 
'myenv/lib/python3.11/site-packages/ffprobe',
'myenv/lib/python3.11/site-packages/ffmpeg',
'/opt/homebrew/bin/ffmpeg',
'/opt/homebrew/bin/ffprobe']
'''
DATA_FILES=[]

"""
OPTIONS = {
    #'includes':['charset_normalizer']
}
"""

OPTIONS={}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)

